server:
  port : 8080
spring:
  application:
    name: mfitestwork
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        jdbc:
        #          batch_size: 100
        query:
          in_clause_parameter_padding: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: false
  datasource:
    name: mfitestwork
    url: jdbc:h2:mem:mfitestwork
    username: h2
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    out-of-order: true

fetch-param:
  thread-pool: 5
  article-thread-limit: 4
  total-article-limit: 40
  buffer-limit: 15
  url: "https://api.spaceflightnewsapi.net/v3/articles"
  black-list-name: blacklist.txt

logging:
  level:
    ROOT: info
    org.springframework.web.reactive.function.client.ExchangeFunctions: trace
    io.minery: trace
    org.hibernate.SQL: INFO
    io.swagger.models.parameters.AbstractSerializableParameter: error
    springfox.documentation.schema.property.CachingModelPropertiesProvider: error
    #    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    #    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org.springframework.r2dbc: INFO
    #    reactor.netty: debug
    reactor.netty.http.client: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
