CREATE SEQUENCE "articles_id_seq"
    MINVALUE 1
    MAXVALUE 10000
    INCREMENT BY 10
    START WITH 1
    NOCACHE
NOCYCLE;

create table articles
(
    id bigint generated by default as identity primary key,
    article_id bigint not null,
    title text not null,
    news_site text not null,
    published_date timestamp,
    article text not null
);

